language: node_js
dist: trusty
sudo: false
node_js:
  - "8"
git:
    submodules: false
install:
  - cd $TRAVIS_BUILD_DIR
  - yarn install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master